name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck --if-present
      - run: npm run test --if-present
      - run: npm run build

      - name: Frontend smoke test
        run: |
          npm run start & 
          sleep 10
          curl -f http://localhost:3000 || exit 1

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: black --check .
      - run: pytest --maxfail=1 --disable-warnings --cov=.
      - run: uvicorn main:app --host 0.0.0.0 --port 8000 &
      - run: sleep 5
      - run: curl -f http://127.0.0.1:8000/health || exit 1
